### PR TITLE
chore(fresh_graphql): support latest version of `package:http`

### PR DESCRIPTION
**Pull request by vytautas-pranskunas-**
Bumped version because latest graphql_flutter depends on http: 1.0.0

### CODE REVIEW

**Comment by vytautas-pranskunas-** [comment]
Any chance it can get reviewed and merged any time soon?

**Comment by felangel** [comment]
> Any chance it can get reviewed and merged any time soon?

Yup will look to get it merged later this afternoon.

**Review by felangel — APPROVED** [review]
LGTM ✅

**Comment by vytautas-pranskunas-** [comment]
Thanks

**Pull request merged**
